(defun color-theme-krig ()
  "Color theme by me."
  (interactive)
  (color-theme-install
   '(color-theme-krig
     ((background-color . "white")
      (background-mode . light)
      (border-color . "#eeeeee")
      (foreground-color . "#222222"))
     ((buffers-tab-face . buffers-tab))
     (default ((t (nil))))
     (blue ((t (:foreground "#666666"))))
     (bold ((t (:bold t ))))
     (bold-italic ((t (:bold t ))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "gray75"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (font-lock-builtin-face ((t (:weight bold :foreground "black"))))
     (font-lock-constant-face ((t (nil))))
     (font-lock-comment-face ((t (:foreground "#888888"))))
     (font-lock-doc-face ((t (:foreground "#cc7777"))))
     (font-lock-doc-string-face ((t (:foreground "#cc7777"))))
     (font-lock-function-name-face ((t (:foreground "black"))))
     (font-lock-keyword-face ((t (:weight bold :foreground "black"))))
     (font-lock-preprocessor-face ((t (:foreground "#666666"))))
     (font-lock-reference-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "#cc7777"))))
     (font-lock-type-face ((t (nil))))
     (font-lock-variable-name-face ((t (nil))))
     (font-lock-warning-face ((t (nil))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75"))))
     (gui-element ((t (:background "gray75"))))
     (highlight ((t (:background "#fff0f0"))))
     (isearch ((t (:background "#CC659A"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (mode-line ((t (:background "#3C3B37" :foreground "#c6b9a6"))))
     (mode-line-hilight ((t (:inherit 'mode-line :background "#27091e"))))
     (mode-line-inactive ((t (:inherit 'mode-line :foreground "#aaaaaa"))))
     (mode-line-buffer-id ((t (:inherit 'mode-line :foreground "#eeeeee" :weight bold))))
     (paren-blink-off ((t (:foreground "gray"))))
     (paren-match ((t (:background "#fff0f0"))))
     (paren-mismatch ((t (nil))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "gray65"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "gray65"))))
     (right-margin ((t (nil))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (nil))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (text-cursor ((t (:background "red" :foreground "gray"))))
     (toolbar ((t (:background "gray75"))))
     (underline ((t (:underline t))))
     (vertical-divider ((t (:background "gray75"))))
     (widget ((t (:size "8pt" :background "gray75"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "dark green"))))
     (widget-field-face ((t (:background "gray85"))))
     (widget-inactive-face ((t (nil))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "gray65"))))
     (tabbar-default-face ((t (:inherit default :background "#3c3b37" :foreground "#c6b9a6" :height 0.7))))
     (tabbar-button-face ((t (:inherit tabbar-default-face))))
     (tabbar-selected-face ((t (:inherit tabbar-button-face :foreground "#cccccc"))))
     (tabbar-unselected-face ((t (:inherit tabbar-button-face))))
     (trailing-whitespace ((((class color)) (:background "#fff0f0")))))))
