;; VARIABLES
(setq visible-bell t)
(fset 'yes-or-no-p 'y-or-n-p)
(show-paren-mode t)
(column-number-mode t)
(global-font-lock-mode t)
(icomplete-mode t)
(auto-compression-mode t)
(setq font-lock-maximum-decoration t)
(add-hook 'text-mode-hook 'auto-fill-mode)
(setq transient-mark-mode t)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
;;(customize-set-variable 'scroll-bar-mode 'right)
(winner-mode 1)
(global-auto-revert-mode t)
(blink-cursor-mode -1)
(global-set-key "\C-z" 'undo)

(setq-default indent-tabs-mode t)
